const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const sqlite3 = require('sqlite3');
const library = require('../library');
const { hashPassword } = require('../auth');
const { request } = require('./helpers');
const temp = fs.mkdtempSync(path.join(os.tmpdir(),'library-stock-test-'));
process.env.LIBRARY_DB_PATH = path.join(temp,'library.db');
test('migration, concurrent requests, retries, rollback, fixed IDs and stock restrictions', async () => {
  const legacy = new sqlite3.Database(process.env.LIBRARY_DB_PATH), lq=library.queries(legacy);
  await lq.run('CREATE TABLE 用户信息 (id INTEGER PRIMARY KEY, 用户名 TEXT UNIQUE, 角色 TEXT, 电话 TEXT, 真实姓名 TEXT, 照片 TEXT, password_hash TEXT)');
  for(const [id,name,role] of [[1,'admin','管理员'],[2,'alice','普通用户'],[3,'bob','普通用户']]) await lq.run('INSERT INTO 用户信息 (id,用户名,角色,password_hash) VALUES (?,?,?,?)',[id,name,role,await hashPassword('library-test-password')]);
  await lq.run('CREATE TABLE 图书信息 (id INTEGER PRIMARY KEY, 书名 TEXT, 库存 INTEGER, 总数 INTEGER)');
  for(const row of [[1,'old-book',1,2],[2,'orphan-book',0,1],[3,'duplicate-title',1,1],[4,'duplicate-title',1,1],[5,'untracked-stock',1,2]]) await lq.run('INSERT INTO 图书信息 VALUES (?,?,?,?)',row);
  await lq.run('CREATE TABLE 借阅信息 (id INTEGER PRIMARY KEY, 用户名 TEXT, 书名 TEXT, 借阅时间 TEXT, 归还时间 TEXT, 借阅状态 TEXT)');
  for(const row of [[10,'alice','old-book','20260917',null,'借阅'],[11,'1','orphan-book','20260917',null,'借阅'],[12,'alice','duplicate-title','20260917','20260917','已还']]) await lq.run('INSERT INTO 借阅信息 VALUES (?,?,?,?,?,?)',row);
  await new Promise(resolve=>legacy.close(resolve));
  const { app,db,ready }=require('../server'),q=library.queries(db);
  try {
    await ready;
    const report=JSON.parse(fs.readFileSync(process.env.LIBRARY_DB_PATH+'.migration-v2.json'));
    assert.equal(report.unresolved.length,2);assert.equal(report.reservedStock[0].count,1);assert.ok(fs.existsSync(report.backup));
    assert.equal((await q.get('SELECT user_id FROM 借阅信息 WHERE id=11')).user_id,null);
    const tokens={};for(const name of ['admin','alice','bob']) tokens[name]=(await request(app,'POST','/api/login',{nickname:name,password:'library-test-password'})).data.token;
    const call=(who,method,url,body)=>request(app,method,url,body,tokens[who]);
    const admin=(method,url,body)=>call('admin',method,url,body);
    const borrow=async(who,bookId,requestId)=>{const b=await q.get('SELECT barcode FROM 图书信息 WHERE id=?',[bookId]);return call(who,'POST','/api/borrowBook',{bookId,requestId,barcode:b.barcode});};
    const ret=(who,recordId)=>call(who,'POST','/api/returnBook',{recordId});
    const add=async(title,total=1)=>{const r=await admin('POST','/api/addBook',{title,total});assert.equal(r.status,200);return r.data.data.id;};
    async function invariant(id) {
      const b=await q.get('SELECT * FROM 图书信息 WHERE id=?',[id]);
      const {n}=await q.get("SELECT COUNT(*) AS n FROM 借阅信息 WHERE book_id=? AND 借阅状态='借阅'",[id]);
      assert.equal(b.库存+n+b.legacy_reserved,b.总数,`book ${id}`);assert.ok(b.库存>=0&&b.库存<=b.总数);
    }
    assert.equal((await request(app,'GET','/api/books/byBarcode?barcode=LIB000001')).status,401);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=LIB000001')).data.book.id,1);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=UNKNOWN')).status,404);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=bad%20code')).status,400);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=LIB000002')).data.book.库存,0);
    const custom=await admin('POST','/api/addBook',{title:'leading-zero',total:2,barcode:'00012345'});
    assert.equal(custom.status,200);assert.equal(custom.data.data.barcode,'00012345');
    assert.equal((await admin('POST','/api/addBook',{title:'duplicate-code',total:1,barcode:'00012345'})).status,409);
    for(const barcode of ['bad code','https://example.com','x'.repeat(65)]) assert.equal((await admin('POST','/api/addBook',{title:'invalid-code',total:1,barcode})).status,400);
    const customId=custom.data.data.id;
    assert.equal((await call('alice','POST','/api/borrowBook',{bookId:customId,requestId:'barcode-mismatch-key',barcode:'LIB000001'})).status,409);
    assert.equal((await call('alice','POST','/api/borrowBook',{bookId:customId,requestId:'barcode-missing-key'})).status,400);
    assert.equal((await q.get('SELECT 库存 FROM 图书信息 WHERE id=?',[customId])).库存,2);
    assert.equal((await admin('POST','/api/saveBook',{id:customId,title:'changed',total:2,barcode:'LIB000001'})).status,409);
    assert.equal((await q.get('SELECT 书名 FROM 图书信息 WHERE id=?',[customId])).书名,'leading-zero');
    await assert.rejects(q.run('UPDATE 图书信息 SET barcode=NULL WHERE id=?',[customId]),{code:'SQLITE_CONSTRAINT'});
    // Decode a real QR image with the exact locally bundled WASM decoder.
    const zxing=require('../../frontend/node_modules/zxing-wasm/dist/cjs/reader/index.js');
    const wasm=fs.readFileSync(path.join(__dirname,'../../frontend/public/wasm/zxing_reader.wasm'));
    assert.ok(wasm.equals(fs.readFileSync(path.join(__dirname,'../../frontend/node_modules/zxing-wasm/dist/reader/zxing_reader.wasm'))));
    zxing.setZXingModuleOverrides({wasmBinary:wasm});
    const writer=require('../../frontend/node_modules/zxing-wasm/dist/cjs/writer/index.js');
    writer.setZXingModuleOverrides({wasmBinary:fs.readFileSync(path.join(__dirname,'../../frontend/node_modules/zxing-wasm/dist/writer/zxing_writer.wasm'))});
    for(const [format,text] of [['EAN-13','9780306406157'],['Code128','LIB000001']]) {
      const encoded=await writer.writeBarcodeToImageFile(text,{format,width:640,height:240,margin:20});
      assert.equal(encoded.error,'');
      const result=await zxing.readBarcodesFromImageFile(encoded.image);
      assert.equal(result[0].text,text,format);
    }
    const png=await require('qrcode').toBuffer('00012345',{type:'png',width:320,margin:4,errorCorrectionLevel:'M'});
    const decoded=await zxing.readBarcodesFromImageFile(new Blob([png]));
    assert.equal(decoded[0].text,'00012345');
    const found=await call('alice','GET','/api/books/byBarcode?barcode='+decoded[0].text);
    assert.equal(found.data.book.id,customId);
    const codeImage=await call('alice','GET','/api/bookCode?bookId='+customId);
    assert.equal(codeImage.status,200);assert.ok(codeImage.data.svg.includes('<svg'));assert.equal(codeImage.data.barcode,'00012345');
    const scanned=await call('alice','POST','/api/borrowBook',{bookId:found.data.book.id,barcode:decoded[0].text,requestId:'decoded-real-qr-key'});
    assert.equal(scanned.status,200);await invariant(customId);
    assert.equal((await ret('alice',scanned.data.data.id)).status,200);
    assert.equal((await admin('POST','/api/saveBook',{id:customId,title:'leading-zero',total:2,barcode:'00099999'})).status,200);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=00012345')).status,404);
    assert.equal((await call('alice','GET','/api/books/byBarcode?barcode=00099999')).status,200);
    assert.equal((await call('alice','POST','/api/borrowBook',{bookId:customId,barcode:'00012345',requestId:'decoded-real-qr-key'})).status,200);
    await invariant(customId);
    const last=await add('last-copy');
    const races=await Promise.all(Array.from({length:20},(_,i)=>borrow(i%2?'alice':'bob',last,`concurrency-key-${i.toString().padStart(4,'0')}`)));
    assert.equal(races.filter(r=>r.status===200).length,1);assert.equal(races.filter(r=>r.status===409).length,19);await invariant(last);
    const dedup=await add('dedup',3),key='same-request-key-0001';
    const dup=await Promise.all(Array.from({length:8},()=>borrow('alice',dedup,key)));
    assert.ok(dup.every(r=>r.status===200));assert.equal(new Set(dup.map(r=>r.data.data.id)).size,1);
    const rid=dup[0].data.data.id;assert.equal((await q.get('SELECT 库存 FROM 图书信息 WHERE id=?',[dedup])).库存,2);
    assert.equal((await borrow('alice',1,key)).status,409);assert.equal((await ret('bob',rid)).status,404);
    const returns=await Promise.all(Array.from({length:8},()=>ret('alice',rid)));
    assert.ok(returns.every(r=>r.status===200));assert.equal(returns.filter(r=>!r.data.data.repeated).length,1);await invariant(dedup);
    const rollback=await add('rollback');
    await q.run(`CREATE TRIGGER fail_insert BEFORE INSERT ON 借阅信息 WHEN NEW.book_id=${rollback} BEGIN SELECT RAISE(ABORT,'injected insert failure'); END`);
    assert.equal((await borrow('alice',rollback,'rollback-key-0001')).status,500);
    assert.equal((await q.get('SELECT 库存 FROM 图书信息 WHERE id=?',[rollback])).库存,1);
    assert.equal((await q.get('SELECT COUNT(*) AS n FROM borrow_requests WHERE request_id=?',['rollback-key-0001'])).n,0);
    await q.run('DROP TRIGGER fail_insert');
    const retried=await borrow('alice',rollback,'rollback-key-0001');assert.equal(retried.status,200);const retryId=retried.data.data.id;
    await q.run(`CREATE TRIGGER fail_stock BEFORE UPDATE OF 库存 ON 图书信息 WHEN NEW.id=${rollback} AND NEW.库存>OLD.库存 BEGIN SELECT RAISE(ABORT,'injected stock failure'); END`);
    assert.equal((await ret('alice',retryId)).status,500);assert.equal((await q.get('SELECT 借阅状态 FROM 借阅信息 WHERE id=?',[retryId])).借阅状态,'借阅');await invariant(rollback);await q.run('DROP TRIGGER fail_stock');
    for(const body of [{title:'x',total:-1},{title:'x',total:1.5},{title:'x',total:1,stock:2},{title:'x',total:2,stock:1},{title:'',total:1}]) assert.equal((await admin('POST','/api/addBook',body)).status,400);
    assert.equal((await admin('POST','/api/saveBook',{id:rollback,title:'x',total:1,stock:-1})).status,400);
    assert.equal((await admin('POST','/api/saveBook',{id:rollback,title:'x',total:0})).status,409);
    assert.equal((await admin('POST','/api/saveBook',{id:rollback,title:'x',total:1,stock:1})).status,409);
    for(const id of [rollback,5]) assert.equal((await admin('POST','/api/deleteBook',{id})).status,409);
    await assert.rejects(q.run('UPDATE 图书信息 SET 库存=-1 WHERE id=?',[rollback]),{code:'SQLITE_CONSTRAINT'});
    await assert.rejects(q.run('UPDATE 图书信息 SET 库存=总数+1 WHERE id=?',[rollback]),{code:'SQLITE_CONSTRAINT'});
    await assert.rejects(q.run("INSERT INTO 借阅信息 (user_id,book_id,用户名,书名,借阅状态) VALUES (99999,1,'bad','bad','借阅')"),{code:'SQLITE_CONSTRAINT'});
    assert.equal((await call('alice','PATCH','/api/me',{nickname:'alice-new'})).status,200);
    assert.equal((await admin('POST','/api/saveBook',{id:rollback,title:'renamed-book',total:2})).status,200);
    assert.equal((await ret('alice',retryId)).status,200);await invariant(rollback);
    const hist=(await call('alice','GET','/api/myBorrowRecords')).data.find(r=>r.id===retryId);assert.equal(hist.用户名,'alice-new');assert.equal(hist.书名,'renamed-book');
    assert.equal((await admin('POST','/api/deleteBook',{id:rollback})).status,200);
    assert.ok(!(await call('alice','GET','/api/books')).data.some(b=>b.id===rollback));assert.ok((await admin('GET','/api/books')).data.some(b=>b.id===rollback&&b.archived));
    assert.equal((await borrow('alice',rollback,'archived-new-key-01')).status,404);assert.equal((await call('alice','GET','/api/books/byBarcode?barcode='+(await q.get('SELECT barcode FROM 图书信息 WHERE id=?',[rollback])).barcode)).status,410);assert.ok((await call('alice','GET','/api/myBorrowRecords')).data.some(r=>r.id===retryId));
    const orphan={id:11,userId:3,bookId:2,status:'借阅',borrowTime:'20260917',returnTime:null};
    assert.equal((await admin('PUT','/api/updateBorrowRecord',orphan)).status,200);assert.equal((await q.get('SELECT migration_issue FROM 借阅信息 WHERE id=11')).migration_issue,null);await invariant(2);assert.equal((await ret('bob',11)).status,200);await invariant(2);
    const edit={id:rid,userId:2,bookId:dedup,status:'借阅',borrowTime:'20260917',returnTime:null};
    assert.equal((await admin('PUT','/api/updateBorrowRecord',edit)).status,200);await invariant(dedup);
    assert.equal((await admin('PUT','/api/updateBorrowRecord',{...edit,borrowTime:'20260230'})).status,400);
    assert.equal((await admin('PUT','/api/updateBorrowRecord',{...edit,status:'已还',returnTime:'20250917'})).status,400);
    assert.equal((await admin('PUT','/api/updateBorrowRecord',{...edit,userId:3})).status,200);
    const replay=await borrow('alice',dedup,key);assert.equal(replay.status,200);assert.equal(replay.data.data.id,rid);await invariant(dedup);
    assert.equal((await admin('PUT','/api/updateBorrowRecord',{...edit,userId:3,status:'已还',returnTime:'20260917'})).status,200);await invariant(dedup);
    const parallel=await add('parallel');const p=await borrow('bob',parallel,'parallel-request-01');
    const mutations=await Promise.all([admin('POST','/api/saveBook',{id:parallel,title:'parallel-new',total:2}),ret('bob',p.data.data.id)]);assert.ok(mutations.every(r=>r.status===200));
    for(const b of await q.all('SELECT id FROM 图书信息')) await invariant(b.id);assert.equal((await q.all('PRAGMA foreign_key_check')).length,0);
  } finally {await new Promise(resolve=>db.close(resolve));fs.rmSync(temp,{recursive:true,force:true});}
});
test('conflicting old inventory rolls back migration and retains backup',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'library-invalid-')),file=path.join(dir,'bad.db'),db=new sqlite3.Database(file),q=library.queries(db);
  try {
    await q.run('CREATE TABLE 用户信息 (id INTEGER PRIMARY KEY, 用户名 TEXT)');await q.run('CREATE TABLE 图书信息 (id INTEGER PRIMARY KEY, 书名 TEXT, 库存 INTEGER, 总数 INTEGER)');await q.run('CREATE TABLE 借阅信息 (id INTEGER PRIMARY KEY, 用户名 TEXT, 书名 TEXT, 借阅时间 TEXT, 归还时间 TEXT, 借阅状态 TEXT)');await q.run("INSERT INTO 图书信息 VALUES (1,'bad',-1,1)");
    await assert.rejects(library.migrate(db,file),/迁移已回滚/);assert.equal((await q.get('SELECT 库存 FROM 图书信息')).库存,-1);assert.ok(!(await q.all('PRAGMA table_info(借阅信息)')).some(c=>c.name==='user_id'));assert.ok(fs.readdirSync(dir).some(f=>f.includes('before-library-v2')));
  } finally {await new Promise(resolve=>db.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
